root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main.exe"
  cmd = "go build -o ./tmp/main.exe ./cmd/app"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"
  stop_on_error = true
